# Generated by Django 2.2.7 on 2021-08-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_APP', '0003_auto_20210819_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='fijo',
            field=models.BooleanField(default=False, verbose_name='Fijo'),
        ),
    ]
