from django.contrib import admin
from CV_APP.models import Monica,opcion, Coordinacion2,Psicologa,Conclusion,Rubrica_demo,Criterios,Rubrica_equipomulti ,Rubrica_coordinador,Rector,Nivel_Tec ,Ingles,Titulo, Años, Cargo, Colegios,Colegios2,Colegios3, Disposicion, Postulacion, User, Rubrica, Rubrica_psicologa, Coordinacion, Nivel_ingles, Aspectos_generales,Competencias
# Register your models here.

admin.site.register(Años)
admin.site.register(Cargo)
admin.site.register(Colegios)
admin.site.register(Colegios2)
admin.site.register(Colegios3)
admin.site.register(Disposicion)
admin.site.register(Postulacion)
admin.site.register(User)
admin.site.register(Rubrica)
admin.site.register(Rubrica_psicologa)
admin.site.register(Coordinacion)
admin.site.register(Coordinacion2)
admin.site.register(Nivel_ingles)
admin.site.register(Aspectos_generales)
admin.site.register(Competencias)
admin.site.register(Titulo)
admin.site.register(Ingles)
admin.site.register(Nivel_Tec)
admin.site.register(Rector)
admin.site.register(Rubrica_coordinador)
admin.site.register(Rubrica_equipomulti)
admin.site.register(Rubrica_demo)
admin.site.register(Criterios)
admin.site.register(Conclusion)
admin.site.register(Psicologa)
admin.site.register(opcion)
admin.site.register(Monica)

